name: Build Unity Windows

on:
  push:
    branches:
      - main  # Le build se lance seulement sur main
  workflow_dispatch:  # Permet de lancer manuellement

jobs:
  build:
    runs-on: ubuntu-latest  # Utilisation d'Ubuntu comme environnement

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Récupère le code source

      - name: Cache Library Folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Set up Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2022.3.9f1  # Mets ta version exacte
          targetPlatform: StandaloneWindows64  # Build pour Windows 64 bits

      - name: Build Windows
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: StandaloneWindows64

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Build
          path: build/StandaloneWindows64/
